name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - run: git fetch --tags --force origin #workaround https://github.com/actions/checkout/issues/882

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew clean build

      - name: Project Version
        id: project-version
        run: |
          output=$(./gradlew -q version)
          project-version=$(echo "$output" | grep -oP 'Version: \K.*')
          echo "project-version=$project-version"
          echo "project-version=$project-version" >> $GITHUB_OUTPUT

      - name: Assemble distribution (Release)
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew assembleDist

      - name: Generate Checksum (Release)
        if: startsWith(github.ref, 'refs/tags/')
        working-directory: ./converter/build/distributions
        run: |
          shasum -a 256 "converter-${{ steps.project-version.outputs.project-version }}.tar.gz" > "converter-${{ steps.project-version.outputs.project-version }}.tar.gz.sha256"
          shasum -a 256 "converter-${{ steps.project-version.outputs.project-version }}.zip" > "converter-${{ steps.project-version.outputs.project-version }}.zip.sha256"  

      - name: Release
        id: release
        uses: softprops/action-gh-release@v2.2.1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            converter/build/distributions/converter-${{ steps.project-version.outputs.project-version }}.tar.gz
            converter/build/distributions/converter-${{ steps.project-version.outputs.project-version }}.tar.gz.sha256
            converter/build/distributions/converter-${{ steps.project-version.outputs.project-version }}.zip
            converter/build/distributions/converter-${{ steps.project-version.outputs.project-version }}.zip.sha256
          body: |
            ** V4 Keystore Converter Release **
          draft: true
          preserve_order: true
          generate_release_notes: true
