name: CI

on:
  push:
    branches:
      - main
    tags:
      - '*'
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - run: git fetch --tags --force origin #workaround https://github.com/actions/checkout/issues/882

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.1
        with:
          java-version: 21
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Build
        run: ./gradlew clean build

      - name: Project Version
        run: ./gradlew version

      - name: Assemble distribution for release
        if: startsWith(github.ref, 'refs/tags/')
        run: ./gradlew assembleDist

      - name: Upload distribution artifacts for release
        uses: actions/upload-artifact@v4
        if: startsWith(github.ref, 'refs/tags/')
        with:
          name: distribution
          path: converter/build/distributions/
          retention-days: 1
          if-no-files-found: error